# country_codes.py

# Country codes for display + phone codes
COUNTRY_CODES = {
    "AF": {"name": "Afghanistan", "phone": "+93"},
    "AL": {"name": "Albania", "phone": "+355"},
    "DZ": {"name": "Algeria", "phone": "+213"},
    "AS": {"name": "American Samoa", "phone": "+1684"},
    "AD": {"name": "Andorra", "phone": "+376"},
    "AO": {"name": "Angola", "phone": "+244"},
    "AI": {"name": "Anguilla", "phone": "+1264"},
    "AQ": {"name": "Antarctica", "phone": "+672"},
    "AG": {"name": "Antigua and Barbuda", "phone": "+1268"},
    "AR": {"name": "Argentina", "phone": "+54"},
    "AM": {"name": "Armenia", "phone": "+374"},
    "AW": {"name": "Aruba", "phone": "+297"},
    "AU": {"name": "Australia", "phone": "+61"},
    "AT": {"name": "Austria", "phone": "+43"},
    "AZ": {"name": "Azerbaijan", "phone": "+994"},
    "BS": {"name": "Bahamas", "phone": "+1242"},
    "BD": {"name": "Bangladesh", "phone": "+880"},
    "BB": {"name": "Barbados", "phone": "+1246"},
    "BY": {"name": "Belarus", "phone": "+375"},
    "BE": {"name": "Belgium", "phone": "+32"},
    "BZ": {"name": "Belize", "phone": "+501"},
    "BJ": {"name": "Benin", "phone": "+229"},
    "BM": {"name": "Bermuda", "phone": "+1441"},
    "BT": {"name": "Bhutan", "phone": "+975"},
    "BO": {"name": "Bolivia", "phone": "+591"},
    "BA": {"name": "Bosnia and Herzegovina", "phone": "+387"},
    "BW": {"name": "Botswana", "phone": "+267"},
    "BR": {"name": "Brazil", "phone": "+55"},
    "BN": {"name": "Brunei", "phone": "+673"},
    "BG": {"name": "Bulgaria", "phone": "+359"},
    "BF": {"name": "Burkina Faso", "phone": "+226"},
    "BI": {"name": "Burundi", "phone": "+257"},
    "KH": {"name": "Cambodia", "phone": "+855"},
    "CM": {"name": "Cameroon", "phone": "+237"},
    "CA": {"name": "Canada", "phone": "+1"},
    "CV": {"name": "Cape Verde", "phone": "+238"},
    "CF": {"name": "Central African Republic", "phone": "+236"},
    "TD": {"name": "Chad", "phone": "+235"},
    "CL": {"name": "Chile", "phone": "+56"},
    "CN": {"name": "China", "phone": "+86"},
    "CO": {"name": "Colombia", "phone": "+57"},
    "KM": {"name": "Comoros", "phone": "+269"},
    "CD": {"name": "Congo (DRC)", "phone": "+243"},
    "CG": {"name": "Congo (Republic)", "phone": "+242"},
    "CR": {"name": "Costa Rica", "phone": "+506"},
    "CI": {"name": "Côte d'Ivoire", "phone": "+225"},
    "HR": {"name": "Croatia", "phone": "+385"},
    "CU": {"name": "Cuba", "phone": "+53"},
    "CY": {"name": "Cyprus", "phone": "+357"},
    "CZ": {"name": "Czech Republic", "phone": "+420"},
    "DK": {"name": "Denmark", "phone": "+45"},
    "DJ": {"name": "Djibouti", "phone": "+253"},
    "DM": {"name": "Dominica", "phone": "+1767"},
    "DO": {"name": "Dominican Republic", "phone": "+1809"},
    "EC": {"name": "Ecuador", "phone": "+593"},
    "EG": {"name": "Egypt", "phone": "+20"},
    "SV": {"name": "El Salvador", "phone": "+503"},
    "GQ": {"name": "Equatorial Guinea", "phone": "+240"},
    "ER": {"name": "Eritrea", "phone": "+291"},
    "EE": {"name": "Estonia", "phone": "+372"},
    "ET": {"name": "Ethiopia", "phone": "+251"},
    "FJ": {"name": "Fiji", "phone": "+679"},
    "FI": {"name": "Finland", "phone": "+358"},
    "FR": {"name": "France", "phone": "+33"},
    "GA": {"name": "Gabon", "phone": "+241"},
    "GM": {"name": "Gambia", "phone": "+220"},
    "GE": {"name": "Georgia", "phone": "+995"},
    "DE": {"name": "Germany", "phone": "+49"},
    "GH": {"name": "Ghana", "phone": "+233"},
    "GR": {"name": "Greece", "phone": "+30"},
    "GD": {"name": "Grenada", "phone": "+1473"},
    "GU": {"name": "Guam", "phone": "+1671"},
    "GT": {"name": "Guatemala", "phone": "+502"},
    "GN": {"name": "Guinea", "phone": "+224"},
    "GW": {"name": "Guinea-Bissau", "phone": "+245"},
    "GY": {"name": "Guyana", "phone": "+592"},
    "HT": {"name": "Haiti", "phone": "+509"},
    "HN": {"name": "Honduras", "phone": "+504"},
    "HK": {"name": "Hong Kong", "phone": "+852"},
    "HU": {"name": "Hungary", "phone": "+36"},
    "IS": {"name": "Iceland", "phone": "+354"},
    "IN": {"name": "India", "phone": "+91"},
    "ID": {"name": "Indonesia", "phone": "+62"},
    "IR": {"name": "Iran", "phone": "+98"},
    "IQ": {"name": "Iraq", "phone": "+964"},
    "IE": {"name": "Ireland", "phone": "+353"},
    "IL": {"name": "Israel", "phone": "+972"},
    "IT": {"name": "Italy", "phone": "+39"},
    "JM": {"name": "Jamaica", "phone": "+1876"},
    "JP": {"name": "Japan", "phone": "+81"},
    "JO": {"name": "Jordan", "phone": "+962"},
    "KZ": {"name": "Kazakhstan", "phone": "+7"},
    "KE": {"name": "Kenya", "phone": "+254"},
    "KI": {"name": "Kiribati", "phone": "+686"},
    "KP": {"name": "North Korea", "phone": "+850"},
    "KR": {"name": "South Korea", "phone": "+82"},
    "KW": {"name": "Kuwait", "phone": "+965"},
    "KG": {"name": "Kyrgyzstan", "phone": "+996"},
    "LA": {"name": "Laos", "phone": "+856"},
    "LV": {"name": "Latvia", "phone": "+371"},
    "LB": {"name": "Lebanon", "phone": "+961"},
    "LS": {"name": "Lesotho", "phone": "+266"},
    "LR": {"name": "Liberia", "phone": "+231"},
    "LY": {"name": "Libya", "phone": "+218"},
    "LI": {"name": "Liechtenstein", "phone": "+423"},
    "LT": {"name": "Lithuania", "phone": "+370"},
    "LU": {"name": "Luxembourg", "phone": "+352"},
    "MO": {"name": "Macau", "phone": "+853"},
    "MK": {"name": "North Macedonia", "phone": "+389"},
    "MG": {"name": "Madagascar", "phone": "+261"},
    "MW": {"name": "Malawi", "phone": "+265"},
    "MY": {"name": "Malaysia", "phone": "+60"},
    "MV": {"name": "Maldives", "phone": "+960"},
    "ML": {"name": "Mali", "phone": "+223"},
    "MT": {"name": "Malta", "phone": "+356"},
    "MH": {"name": "Marshall Islands", "phone": "+692"},
    "MR": {"name": "Mauritania", "phone": "+222"},
    "MU": {"name": "Mauritius", "phone": "+230"},
    "MX": {"name": "Mexico", "phone": "+52"},
    "FM": {"name": "Micronesia", "phone": "+691"},
    "MD": {"name": "Moldova", "phone": "+373"},
    "MC": {"name": "Monaco", "phone": "+377"},
    "MN": {"name": "Mongolia", "phone": "+976"},
    "ME": {"name": "Montenegro", "phone": "+382"},
    "MA": {"name": "Morocco", "phone": "+212"},
    "MZ": {"name": "Mozambique", "phone": "+258"},
    "MM": {"name": "Myanmar", "phone": "+95"},
    "NA": {"name": "Namibia", "phone": "+264"},
    "NR": {"name": "Nauru", "phone": "+674"},
    "NP": {"name": "Nepal", "phone": "+977"},
    "NL": {"name": "Netherlands", "phone": "+31"},
    "NZ": {"name": "New Zealand", "phone": "+64"},
    "NI": {"name": "Nicaragua", "phone": "+505"},
    "NE": {"name": "Niger", "phone": "+227"},
    "NG": {"name": "Nigeria", "phone": "+234"},
    "NO": {"name": "Norway", "phone": "+47"},
    "OM": {"name": "Oman", "phone": "+968"},
    "PK": {"name": "Pakistan", "phone": "+92"},
    "PW": {"name": "Palau", "phone": "+680"},
    "PA": {"name": "Panama", "phone": "+507"},
    "PG": {"name": "Papua New Guinea", "phone": "+675"},
    "PY": {"name": "Paraguay", "phone": "+595"},
    "PE": {"name": "Peru", "phone": "+51"},
    "PH": {"name": "Philippines", "phone": "+63"},
    "PL": {"name": "Poland", "phone": "+48"},
    "PT": {"name": "Portugal", "phone": "+351"},
    "PR": {"name": "Puerto Rico", "phone": "+1787"},
    "QA": {"name": "Qatar", "phone": "+974"},
    "RO": {"name": "Romania", "phone": "+40"},
    "RU": {"name": "Russia", "phone": "+7"},
    "RW": {"name": "Rwanda", "phone": "+250"},
    "KN": {"name": "Saint Kitts and Nevis", "phone": "+1869"},
    "LC": {"name": "Saint Lucia", "phone": "+1758"},
    "VC": {"name": "Saint Vincent and the Grenadines", "phone": "+1784"},
    "WS": {"name": "Samoa", "phone": "+685"},
    "SM": {"name": "San Marino", "phone": "+378"},
    "ST": {"name": "Sao Tome and Principe", "phone": "+239"},
    "SA": {"name": "Saudi Arabia", "phone": "+966"},
    "SN": {"name": "Senegal", "phone": "+221"},
    "RS": {"name": "Serbia", "phone": "+381"},
    "SC": {"name": "Seychelles", "phone": "+248"},
    "SL": {"name": "Sierra Leone", "phone": "+232"},
    "SG": {"name": "Singapore", "phone": "+65"},
    "SK": {"name": "Slovakia", "phone": "+421"},
    "SI": {"name": "Slovenia", "phone": "+386"},
    "SB": {"name": "Solomon Islands", "phone": "+677"},
    "SO": {"name": "Somalia", "phone": "+252"},
    "ZA": {"name": "South Africa", "phone": "+27"},
    "ES": {"name": "Spain", "phone": "+34"},
    "LK": {"name": "Sri Lanka", "phone": "+94"},
    "SD": {"name": "Sudan", "phone": "+249"},
    "SR": {"name": "Suriname", "phone": "+597"},
    "SE": {"name": "Sweden", "phone": "+46"},
    "CH": {"name": "Switzerland", "phone": "+41"},
    "SY": {"name": "Syria", "phone": "+963"},
    "TW": {"name": "Taiwan", "phone": "+886"},
    "TJ": {"name": "Tajikistan", "phone": "+992"},
    "TZ": {"name": "Tanzania", "phone": "+255"},
    "TH": {"name": "Thailand", "phone": "+66"},
    "TL": {"name": "Timor-Leste", "phone": "+670"},
    "TG": {"name": "Togo", "phone": "+228"},
    "TO": {"name": "Tonga", "phone": "+676"},
    "TT": {"name": "Trinidad and Tobago", "phone": "+1868"},
    "TN": {"name": "Tunisia", "phone": "+216"},
    "TR": {"name": "Turkey", "phone": "+90"},
    "TM": {"name": "Turkmenistan", "phone": "+993"},
    "TV": {"name": "Tuvalu", "phone": "+688"},
    "UG": {"name": "Uganda", "phone": "+256"},
    "UA": {"name": "Ukraine", "phone": "+380"},
    "AE": {"name": "United Arab Emirates", "phone": "+971"},
    "GB": {"name": "United Kingdom", "phone": "+44"},
    "US": {"name": "United States", "phone": "+1"},
    "UY": {"name": "Uruguay", "phone": "+598"},
    "UZ": {"name": "Uzbekistan", "phone": "+998"},
    "VU": {"name": "Vanuatu", "phone": "+678"},
    "VE": {"name": "Venezuela", "phone": "+58"},
    "VN": {"name": "Vietnam", "phone": "+84"},
    "YE": {"name": "Yemen", "phone": "+967"},
    "ZM": {"name": "Zambia", "phone": "+260"},
    "ZW": {"name": "Zimbabwe", "phone": "+263"}
}